### ISSUE TITLE
Interactive chat box

### ISSUE THREAD

**Issue by MerveKucukzoroglu** [Befa79/hackathon-mindfulness#12]
We encountered a few bugs while trying to deploy our Interactive chatbot to the website alongside our other features.

we aimed for: [chatbot example](https://user-images.githubusercontent.com/65243328/151778041-74c0d3f1-e226-4af3-9a0e-6a6ad6aa7584.JPG)

Bugs that showed up: [chatbot error](https://user-images.githubusercontent.com/65243328/151778281-3dbe81cc-5a35-47ba-92c8-f5abd7ad5e23.JPG)

We tried to install Flask to get the Python app to run through however this did not configure properly.
In the future we hope to work on this to get the Interactive chatbot fully functional so users can interact with their Mental Health partner in the LiveChat.

**Comment by MikaCodez** [comment]
Have written bugs in Readme as for Interactive Chatbot not working in Website.
